### ISSUE TITLE
600MB of test log files are being included in published gems

### ISSUE THREAD

**Issue by cyclotron3k** [locoframework/loco-rails#15]
Everything in the test directory is being included in the packaged and published gem, leading to gems that are ~60MB compressed, (~600MB decompressed)

Including tests in the gems is not strictly necessary:
https://stackoverflow.com/questions/37800233/should-one-include-tests-in-a-packaged-gem

**Comment by cyclotron3k** [comment]
The other solution is to only include files that are tracked by git.

A newly scaffolded gem includes this line in the gemspec file:

```ruby
	spec.files         = Dir.chdir(File.expand_path('..', __FILE__)) do
		`git ls-files -z`.split("\x0").reject { |f| f.match(%r{^(test|spec|features)/}) }
	end
```
...which could be modified to include tests, if you really wanted.

**Comment by himn1** [comment]
fixed in https://github.com/locoframework/loco-rails/pull/16
